version: "3.1"

services:
  frontend:
    build: .
    restart: on-failure
    environment:
      SERVER_HOSTNAME: example.com
      SERVER_PORT: 80

  nginx:
    build: ./services/nginx
    restart: on-failure
    ports:
      - 8080:80
    depends_on:
      - frontend
